# Generated by Django 5.1.3 on 2024-11-16 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comensal',
            fields=[
                ('cedula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_ingrediente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo_menu', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('num_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.PositiveIntegerField()),
                ('estado_mesa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mesero',
            fields=[
                ('id_mesero', models.AutoField(primary_key=True, serialize=False)),
                ('salario', models.PositiveIntegerField()),
                ('turno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.PositiveIntegerField()),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_platos', models.PositiveIntegerField()),
                ('total_pago', models.PositiveIntegerField()),
                ('ced_comensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.comensal')),
                ('id_mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.mesero')),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('pago_total', models.PositiveIntegerField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='mesero',
            name='id_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.personal'),
        ),
        migrations.CreateModel(
            name='cocinero',
            fields=[
                ('id_cocinero', models.AutoField(primary_key=True, serialize=False)),
                ('salario', models.PositiveIntegerField()),
                ('turno', models.CharField(max_length=50)),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.personal')),
            ],
        ),
        migrations.CreateModel(
            name='plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_plato', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.menu')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.plato'),
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('num_personas', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('cedula_comensal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.comensal')),
                ('num_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='ingredientes_plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.ingrediente')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.plato')),
            ],
            options={
                'unique_together': {('id_ingrediente', 'id_plato')},
            },
        ),
        migrations.CreateModel(
            name='prepara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cocinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.cocinero')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurante.plato')),
            ],
            options={
                'unique_together': {('id_plato', 'id_cocinero')},
            },
        ),
    ]
